Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  4.0.170.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Make User Like Edit Data Form' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Edit, "352e0477-9345-4504-a537-5c1761724140", "4e8379d7-c922-4398-8cb0-bf2b0ff232ae", "")>
Partial Public Class [MakeUserLikeEditDataFormUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _sourceuser As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of System.Guid)
    Private WithEvents _userlist As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of MakeUserLikeEditDataFormUSERLISTUIModel)

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.170.0")> _
    Public Sub New()
        MyBase.New()

        _sourceuser = New Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of System.Guid)
        _userlist = New Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of MakeUserLikeEditDataFormUSERLISTUIModel)

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Edit
        MyBase.DataFormTemplateId = New System.Guid("352e0477-9345-4504-a537-5c1761724140")
        MyBase.DataFormInstanceId = New System.Guid("4e8379d7-c922-4398-8cb0-bf2b0ff232ae")
        MyBase.RecordType = ""
        MyBase.FORMHEADER.Value = "Make Users's Security Like Source User's"
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/blackbaud.customfx.massuserroleassignment/MakeUserLikeEditDataForm.html"

        '
        '_sourceuser
        '
        _sourceuser.Name = "SOURCEUSER"
        _sourceuser.Caption = "Source User"
        _sourceuser.SearchListId = New System.Guid("f51b8ec1-54d4-45e3-86cd-562034137304")
        _sourceuser.EnableQuickFind = True
        _sourceuser.EnableAutoSearch = True
        Me.Fields.Add(_sourceuser)
        '
        '_userlist
        '
        _userlist.Name = "USERLIST"
        _userlist.Caption = "Choose Users"
        Me.Fields.Add(_userlist)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Source User
    ''' </summary>
    <System.ComponentModel.Description("Source User")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.170.0")> _
    Public ReadOnly Property [SOURCEUSER]() As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of System.Guid)
        Get
            Return _sourceuser
        End Get
    End Property
    
    ''' <summary>
    ''' Choose Users
    ''' </summary>
    <System.ComponentModel.Description("Choose Users")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.170.0")> _
    Public ReadOnly Property [USERLIST]() As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of MakeUserLikeEditDataFormUSERLISTUIModel)
        Get
            Return _userlist
        End Get
    End Property
    
End Class
