Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  4.0.170.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'MultiUserSecurityAssignmentEditDataFormROLELIST' data form
''' </summary>
Partial Public Class [MultiUserSecurityAssignmentEditDataFormROLELISTUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.UIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _id As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
    Private WithEvents _rolename As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _selected As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.170.0")> _
    Public Sub New()
        MyBase.New()

        _id = New Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        _rolename = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _selected = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField

        '
        '_id
        '
        _id.Name = "ID"
        _id.Caption = "ID"
        _id.Visible = False
        _id.Enabled = False
        Me.Fields.Add(_id)
        '
        '_rolename
        '
        _rolename.Name = "ROLENAME"
        _rolename.Caption = "RoleName"
        _rolename.DBReadOnly = True
        _rolename.Enabled = False
        Me.Fields.Add(_rolename)
        '
        '_selected
        '
        _selected.Name = "SELECTED"
        _selected.Caption = "Selected"
        Me.Fields.Add(_selected)

		OnCreated()

    End Sub
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.170.0")> _
    Public ReadOnly Property [ID]() As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        Get
            Return _id
        End Get
    End Property
    
    ''' <summary>
    ''' RoleName
    ''' </summary>
    <System.ComponentModel.Description("RoleName")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.170.0")> _
    Public ReadOnly Property [ROLENAME]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _rolename
        End Get
    End Property
    
    ''' <summary>
    ''' Selected
    ''' </summary>
    <System.ComponentModel.Description("Selected")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.170.0")> _
    Public Shadows ReadOnly Property [SELECTED]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _selected
        End Get
    End Property
    
End Class
