Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  4.0.170.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'User Role Assignment Summary Section View Data Form' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.View, "d5820509-5290-48ac-bd9c-b4cfeea726a7", "810fc65c-65eb-4155-b9a5-76de8d48cd67", "")>
Partial Public Class [UserRoleAssignmentSummarySectionViewDataFormUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _message As Global.Blackbaud.AppFx.UIModeling.Core.StringField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.170.0")> _
    Public Sub New()
        MyBase.New()

        _message = New Global.Blackbaud.AppFx.UIModeling.Core.StringField

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.View
        MyBase.DataFormTemplateId = New System.Guid("d5820509-5290-48ac-bd9c-b4cfeea726a7")
        MyBase.DataFormInstanceId = New System.Guid("810fc65c-65eb-4155-b9a5-76de8d48cd67")
        MyBase.RecordType = ""
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/blackbaud.customfx.massuserroleassignment/UserRoleAssignmentSummarySectionViewDataForm.html"

        '
        '_message
        '
        _message.Name = "MESSAGE"
        _message.Caption = "User Assignment"
        _message.DBReadOnly = True
        _message.MaxLength = 4000
        _message.Multiline = True
        Me.Fields.Add(_message)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' User Assignment
    ''' </summary>
    <System.ComponentModel.Description("User Assignment")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.170.0")> _
    Public ReadOnly Property [MESSAGE]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _message
        End Get
    End Property
    
End Class
